pipeline:
  publish:
    image: plugins/docker
    repo: plugins/ecr
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: ECR
  desc: Build and publish images to a AWS ECR
  type: publish
  image: plugins/ecr
  labels:
    - docker
    - image
    - container
    - ecr
    - aws
