publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-ecr
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-ecr
    tag: develop
    when:
      branch: develop

plugin:
  name: ECR
  desc: Build and publish images to a AWS ECR
  type: publish
  image: plugins/drone-ecr
  labels:
    - docker
    - image
    - container
    - ecr
    - aws
