pipeline:
  latest:
    image: docker
    repo: plugins/ecr
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: ECR
  desc: Build and publish images to a AWS ECR
  type: publish
  image: plugins/drone-ecr
  labels:
    - docker
    - image
    - container
    - ecr
    - aws
